export const MEMBERS = [
  {
    id: 1,
    name: "Charles Meads",
    position: "Member",
    photo: "https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=*",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 2,
    name: "Eduardo Tollemache",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 3,
    name: "Sari Tayloe",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 4,
    name: "Helena Filipczynski",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 5,
    name: "Elmer Tremaine",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 6,
    name: "Stillmann Di Giacomo",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 7,
    name: "Ashby Vaan",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 8,
    name: "Ali Cambling",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 9,
    name: "Abbe Daniau",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 10,
    name: "Bordie Melwall",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 11,
    name: "Matilde Boast",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 12,
    name: "Rachael Speake",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 13,
    name: "Teodoor Bradforth",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 14,
    name: "Arv Pittoli",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 15,
    name: "Teodora Scay",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 16,
    name: "Dayna Todeo",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 17,
    name: "Alli Lanning",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 18,
    name: "Rube Powe",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 19,
    name: "Julie Record",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 20,
    name: "Nichol Dickens",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 21,
    name: "Jervis Issacof",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 22,
    name: "Nealson Scarfe",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 23,
    name: "Rocky Burren",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 24,
    name: "Adolphe Maxwaile",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 25,
    name: "Melania Clarkin",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 26,
    name: "Chandra Petty",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 27,
    name: "Perry Gutans",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 28,
    name: "Camille Berrygun",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 29,
    name: "Elyssa Paske",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 30,
    name: "Ly Hylton",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 31,
    name: "Montgomery Oakwell",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 32,
    name: "Julee McKnish",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 33,
    name: "Myles Claye",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 34,
    name: "Ealasaid Nurcombe",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 35,
    name: "Hercules Spellar",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 36,
    name: "Orv Everit",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 37,
    name: "Ninnetta Ligertwood",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 38,
    name: "Herbert Quilligan",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 39,
    name: "Gardie Kliemann",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 40,
    name: "Cassi Kennion",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 41,
    name: "Rebekkah Davidow",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 42,
    name: "Perceval Zorzini",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 43,
    name: "Pietro Mushet",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 44,
    name: "Klemens Paulon",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 45,
    name: "Anson Heintz",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 46,
    name: "Bernie Cometti",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 47,
    name: "Leeann Avison",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 48,
    name: "Mignonne Lidstone",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 49,
    name: "Nickie Fitzsimon",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 50,
    name: "Addi Woodroof",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 51,
    name: "Cleve Clemente",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 52,
    name: "Grace Greenly",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 53,
    name: "Dorella Pinilla",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 54,
    name: "Franciska Piatti",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 55,
    name: "Flori Balaison",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 56,
    name: "Stephen Kayes",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 57,
    name: "Bernie Aire",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 58,
    name: "Maison Bello",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 59,
    name: "Donovan Folliss",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 60,
    name: "Amalle Michelet",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 61,
    name: "Laurena Triggol",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 62,
    name: "Rodd Peeters",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 63,
    name: "Frasier Sails",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 64,
    name: "Marielle Branigan",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 65,
    name: "Sergio Girardin",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 66,
    name: "Evelyn Aikenhead",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 67,
    name: "Melosa Castilla",
    position: "Member",
    photo: "https://placehold.co/400",
    linkedIn: "error: Illegal quoting in line 1.",
    officer: false,
  },
  {
    id: 68,
    name: "David Loder",
    position: "President",
    photo: "/images/uploads/DAvidLoder.jpg",
    linkedIn: "https://www.linkedin.com/in/daveloder/",
    officer: true,
  },
  {
    id: 69,
    name: "Elle Nyugen",
    position: "Vice President",
    photo: "/images/uploads/ElleNyugen.jpg",
    linkedIn: "https://www.linkedin.com/in/elle-nguyen-124177225/",
    officer: true,
  },
  {
    id: 70,
    name: "Jeffin Johnykutty",
    position: "TBD",
    photo: "/images/uploads/PhotoPicJeffinCropped.jpg",
    linkedIn: "",
    officer: true,
  },
];
