export const PROJECTS = [
  {
    id: 1,
    projectTitle: "Why you need a home NAS. ",
    projectDescription:
      "A short project on why you need a home Network Accessed Server demostrated using TrueNas Scale",
    projectAuthor: "David Loder",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "February 2024",
  },
  {
    id: 2,
    projectTitle: "Playing Minecraft with your Hands",
    projectDescription:
      "How to create gesture interface for your webcam to play Minecraft",
    projectAuthor: "Jayming Liu",
    projectLink:
      "https://github.com/Capstone-Projects-2024-Spring/project-motion",
    githubLink:
      "https://github.com/Capstone-Projects-2024-Spring/project-motion",
    featuredProject: true,
    projectDate: "April 2024",
  },
  {
    id: 3,
    projectTitle: "Wordpress and Why You Should Use It",
    projectDescription:
      "Why you need a website, using Avata a WordPress plugin",
    projectAuthor: "Josh O'Halloran",
    projectLink: "https://joshuaohalloran.me",
    githubLink: "",
    featuredProject: true,
    projectDate: "April 2024",
  },
  {
    id: 4,
    projectTitle: "CookBook Pro",
    projectDescription: "A Receipe and Meal Planner App build on ReactJS",
    projectAuthor: "Shawn Dutill",
    projectLink: "https://cookbook-pro-49b95.firebaseapp.com/",
    githubLink:
      "https://github.com/Capstone-Projects-2024-Spring/project-cookbook-pro",
    featuredProject: true,
    projectDate: "April 2024",
  },
  {
    id: 5,
    projectTitle: "Scheduler Complier",
    projectDescription:
      "A breadth-frist schedule complier app for Temple University",
    projectAuthor: "Eric Reizas",
    projectLink: "https://www.youtube.com/watch?v=sdSEkCOxR30",
    githubLink: "https://github.com/cis3296f23/01-Schedule-Compiler",
    featuredProject: true,
    projectDate: "April 2024",
  },
  {
    id: 6,
    projectTitle: "JavaScript Games",
    projectDescription: "No Description",
    projectAuthor: "Jacob Snarr",
    projectLink: "",
    githubLink: "",
    featuredProject: true,
    projectDate: "December 2023",
  },
  {
    id: 7,
    projectTitle: "Riot API & LoL Data Analysis",
    projectDescription:
      "A simple program that pulling data on a League of Legends account from the Riot Games API.",
    projectAuthor: "Shawn Dutill",
    projectLink: "",
    githubLink: "https://github.com/sdutill",
    featuredProject: false,
    projectDate: "November 2023",
  },
  {
    id: 8,
    projectTitle: "IVR Tool For Faculty",
    projectDescription: "No Description",
    projectAuthor: "Neil Conley",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "November 2023",
  },
  {
    id: 9,
    projectTitle: "CHIP-8 in JavaScript",
    projectDescription: "No Description",
    projectAuthor: "Jacob Snarr",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "November 2023",
  },

  {
    id: 10,
    projectTitle: "Calculator Project",
    projectDescription: "No Description",
    projectAuthor: "Jacob Shin",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "November 2023",
  },

  {
    id: 12,
    projectTitle: "Chess Engine",
    projectDescription: "No Description",
    projectAuthor: "Brian Ervin",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "October 2023",
  },
  {
    id: 13,
    projectTitle: "Appropriate Music Separator",
    projectDescription: "No Description",
    projectAuthor: "Eric Reizas",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "October 2023",
  },
  {
    id: 14,
    projectTitle: "SEC schedule of investments web scrapper",
    projectDescription: "No Description",
    projectAuthor: "Tony Siu",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "October 2023",
  },
  {
    id: 15,
    projectTitle: "BimlFlex Documentation Webapp Demo",
    projectDescription: "No Description",
    projectAuthor: "Shawn Dutill & John Currie",
    projectLink: "https://bimlflexdocappdemo.web.app/#",
    githubLink: "",
    featuredProject: false,
    projectDate: "October 2023",
  },
  {
    id: 16,
    projectTitle: "Excel Deltas",
    projectDescription: "No Description",
    projectAuthor: "Shawn Dutill",
    projectLink: "",
    githubLink: "https://github.com/sdutill",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 17,
    projectTitle: "Conveyor Belts",
    projectDescription: "No Description",
    projectAuthor: "Tyler Schemaitat",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 18,
    projectTitle: "Raff",
    projectDescription: "No Description",
    projectAuthor: "Alex McGinn",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 19,
    projectTitle: "Hangman in C",
    projectDescription:
      "Hangman program recreated in C, originally written in Java.",
    projectAuthor: "Francis R Scallatino",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 20,
    projectTitle: "Weather and NBA Report",
    projectDescription: "No Description",
    projectAuthor: "Eric Reizas",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 21,
    projectTitle: "Philly Tree Map",
    projectDescription: "No Description",
    projectAuthor: "John Currie",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 22,
    projectTitle: "Cheater's Hangman",
    projectDescription: "No Description",
    projectAuthor: "Amitai Goldmeer",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
  {
    id: 23,
    projectTitle: "Blackhole Simulation and GPU programming",
    projectDescription:
      "How to render a 3D model of a black hole using GPU programming",
    projectAuthor: "David Palomino",
    projectLink: "",
    githubLink: "",
    featuredProject: true,
    projectDate: "February 2024",
  },
  {
    id: 24,
    projectTitle: "Morse Code Translator",
    projectDescription: "No Description",
    projectAuthor: "Riley Riley",
    projectLink: "",
    githubLink: "",
    featuredProject: false,
    projectDate: "Spring 2023",
  },
];
